[phases.setup]
nixPkgs = [
  "nodejs_20",
  "nss",
  "cups",
  "libdrm",
  "atk",
  "at-spi2-atk",
  "gtk3",
  "libxkbcommon",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "expat",
  "xorg.libxcb"
]
aptPkgs = [
  "chromium",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgbm1",
  "libasound2t64",
  "libpangocairo-1.0-0",
  "libxss1",
  "libgtk-3-0",
  "libxshmfence1",
  "libglu1-mesa"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = []

[start]
cmd = "node src/index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
TZ = "America/Sao_Paulo"
